# This is a basic workflow to help you get started with Actions

name: Sphinx Docs Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch

on:
  push:
    branches:
      - dev
      - feature/sphinx-cicd
    paths:
      - 'docs/**'
      - '.github/workflows/deploy_sphinx_docs.yml'


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Build Sphinx
    - name: Sphinx Build
      uses: ammaraskar/sphinx-action@0.4
      with:
        # The folder containing your sphinx docs.
        docs-folder: docs/
        # The command used to build your documentation.
        build-command: make html
        # Run before the build command, you can use this to install system level dependencies, for example with "apt-get update -y && apt-get install -y perl"
        #pre-build-command: # optional

    - name: Commit documentation changes
      run: |
        git clone https://github.com/pkgpkr/Package-Picker.git --branch gh-pages --single-branch gh-pages
        cd gh-pages
        rm -r *
        cp -r ../docs/build/html/* gh-pages/
        touch .nojekyll
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, so we ignore
        # the return code.
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GH_TOKEN }}
