# This is a basic workflow to help you get started with Actions

name: Sphinx Docs Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    paths:
      - 'docs/**'
      - '.github/workflows/test_sphinx_docs.yml'
  pull_request:
    paths:
      - 'docs/**'
      - '.github/workflows/test_sphinx_docs.yml'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Build Sphinx
    - name: Sphinx Build
      uses: ammaraskar/sphinx-action@0.4
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GITHUB_CLIENT_ID: "dummy"
        GITHUB_CLIENT_SECRET: "dummy"
        DB_HOST: "dummy"
        DB_PORT: "dummy"
        DB_DATABASE: "dummy"
        DB_USER: "dummy"
        DB_PASSWORD: "dummy"
      with:
        # The folder containing your sphinx docs.
        docs-folder: docs/
        # The command used to build your documentation.
        build-command: make html
        # Run before the build command, you can use this to install system level dependencies, for example with "apt-get update -y && apt-get install -y perl"
        pre-build-command: export GITHUB_CLIENT_ID=dummy
